In [9]:
#basic operations in pytorch

import torch

x=torch.randn(3, requires_grad=True) #tensor of size 3, random n from std normal distribution( mean 0, variance 1)
#requires_grad is used to indicate whether a tensor should be tracking operations that involve for automaticc diff
#computes gradient of the outpt tensor if true

print(x)

y=x+2
print(y)

z=y.mean()
print(z)

tensor([ 0.3132, -0.8858, -0.5328], requires_grad=True)
tensor([2.3132, 1.1142, 1.4672], grad_fn=<AddBackward0>)
tensor(1.6315, grad_fn=<MeanBackward0>)


In [18]:
#tensors
#gradient descent

w = torch.ones(4, requires_grad=True)

for epoch in range (2):
    model_output= (w*3).sum()
    
    model_output.backward() #backpropogation, computes gradients of a loss fn
    #loss fn criterion like cross entropy or mean sqaured error
    #graidents then used by optimizer called adam, SGD ie stochastic gradient descent etc
    print(w.grad)
    w.grad.zero_() #to empty gradients

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [25]:
#Backpropogation


x=torch.tensor(1.0)
y=torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)
#forward
y_hat = w*x

lossfn = (y_hat - y)**2

print(lossfn)

#backward pass
lossfn.backward()
print(w.grad) #first value after back propogation


##### update weights




tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [27]:
# implementing simple linear regression and manula graident calculation
import numpy as np

### f= w*x
# f=2*x

x=np.array([1,2,3,4,], dtype=np.float32)
y=np.array([2,4,6,8,], dtype=np.float32)
w=0.0

#model prediction

def forwardfn(x):
    return w*x #y_predicted

#calc  loss = MSE
def loss(y, y_predicted): #model output
    return ((y_predicted - y)**2).mean()

#calculate gradients manually using formuala
#MSE = 1/N * (w*x - y)**2
#erivtitive is 1/N 2x (w*x - y)
def gradient(x, y, y_predited): #dependent on x,y , y_predicted
    return np.dot(2*x, y_predited - y).mean()


# predictions before training

print('f(5) = {forward(5):.3f}')

learning_rate = 0.01
iterations = 20

for epoch in range(iterations):
    #forward pass
    y_pred =  forwardfn(x)
    
    l = loss(y, y_pred)
    
    dw = gradient(x,y,y_pred)
    
    w-= learning_rate*dw


if epoch %1 ==0:
    print(f'epoch {epoch+1}: w={w:.3f}, loss={l:.8f}')



f(5) = {forward(5):.3f}
epoch 20: w=2.000, loss=0.00000000
